export const ENABLE_ACTIVE = 'ENABLE_ACTIVE';
export const DISABLE_ACTIVE = 'DISABLE_ACTIVE';
export const UPDATE_CHART_ITEM = 'UPDATE_CHART_ITEM';
export const UPDATE_CHART_ITEM_CHARTLIST = 'UPDATE_CHART_ITEM_CHARTLIST'
export const UPDATE_CHART_ITEM_ONE = 'UPDATE_CHART_ITEM_ONE'
export const UPDATE_CHART_ITEM_CHARTLIST_ONE = 'UPDATE_CHART_ITEM_CHARTLIST_ONE'
export const UPDATE_PROP = 'UPDATE_PROP'
export const UPDATE_RENDER_VIEW = 'UPDATE_RENDER_VIEW'
export const UPDATE_CURRENT_PROP = 'UPDATE_CURRENT_PROP'
export const ADD_PROP = 'ADD_PROP'
export const UPDATE_CHART_TYPE = 'UPDATE_CHART_TYPE'

export default {
    ENABLE_ACTIVE,
    DISABLE_ACTIVE,
    UPDATE_CHART_ITEM,
    UPDATE_CHART_ITEM_CHARTLIST,
    UPDATE_CHART_ITEM_ONE,
    UPDATE_CHART_ITEM_CHARTLIST_ONE,
    UPDATE_PROP,
    UPDATE_RENDER_VIEW,
    UPDATE_CURRENT_PROP,
    ADD_PROP,
    UPDATE_CHART_TYPE
}